# -*- encoding: utf-8 -*-

=begin
#Patch API V1

#The core API used to integrate with Patch's service

The version of the OpenAPI document: v1
Contact: developers@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "patch_ruby/version"

Gem::Specification.new do |s|
  s.name        = "patch_ruby"
  s.version     = Patch::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["developers@usepatch.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Patch API V1 Ruby Gem"
  s.description = "The core API used to integrate with Patch's service"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
