=begin
#Patch API V1

#The core API used to integrate with Patch's service

The version of the OpenAPI document: v1
Contact: developers@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Patch::EstimatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EstimatesApi' do
  before do
    # run before each test
    @api_instance = Patch::EstimatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EstimatesApi' do
    it 'should create an instance of EstimatesApi' do
      expect(@api_instance).to be_instance_of(Patch::EstimatesApi)
    end
  end

  # unit tests for create_mass_estimate
  # Create an estimate based on mass of CO2
  # Creates an estimate for the mass of CO2 to be compensated. An order in the &#x60;draft&#x60; state will also be created, linked to the estimate. 
  # @param create_mass_estimate_request 
  # @param [Hash] opts the optional parameters
  # @return [EstimateResponse]
  describe 'create_mass_estimate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_estimate
  # Retrieves an estimate
  # Retrieves a given estimate and its associated order. You can only retrieve estimates associated with the organization you are querying for. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [EstimateResponse]
  describe 'retrieve_estimate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_estimates
  # Retrieves a list of estimates
  # Retrieves a list of estimates and their associated orders. You can only retrieve estimates associated with the organization you are querying for. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @return [EstimateListResponse]
  describe 'retrieve_estimates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
