=begin
#Patch API V1

#The core API used to integrate with Patch's service

The version of the OpenAPI document: v1
Contact: developers@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for PatchRuby::ProjectsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProjectsApi' do
  before do
    # run before each test
    @api_instance = PatchRuby::ProjectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectsApi' do
    it 'should create an instance of ProjectsApi' do
      expect(@api_instance).to be_instance_of(PatchRuby::ProjectsApi)
    end
  end

  # unit tests for retrieve_project
  # Retrieves a project
  # Retrieves a project available on Patch&#39;s platform. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ProjectResponse]
  describe 'retrieve_project test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_projects
  # Retrieves a list of projects
  # Retrieves a list of projects available for purchase on Patch&#39;s platform. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @return [ProjectListResponse]
  describe 'retrieve_projects test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
