=begin
#Patch API V1

#The core API used to integrate with Patch's service

The version of the OpenAPI document: v1
Contact: developers@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Patch::TechnologyTypesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TechnologyTypesApi' do
  before do
    # run before each test
    @api_instance = Patch::TechnologyTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TechnologyTypesApi' do
    it 'should create an instance of TechnologyTypesApi' do
      expect(@api_instance).to be_instance_of(Patch::TechnologyTypesApi)
    end
  end

  # unit tests for retrieve_technology_types
  # Retrieves the list of technology_types
  # Retrieves a list of all technology_types. 
  # @param [Hash] opts the optional parameters
  # @return [TechnologyTypeListResponse]
  describe 'retrieve_technology_types test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
