=begin
#Patch API V1

#The core API used to integrate with Patch's service

The version of the OpenAPI document: v1
Contact: developers@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Patch::CreateProjectRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Patch::CreateProjectRequest do
  let(:instance) { Patch::CreateProjectRequest.new }

  describe 'test an instance of CreateProjectRequest' do
    it 'should create an instance of CreateProjectRequest' do
      expect(instance).to be_instance_of(Patch::CreateProjectRequest)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "country"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["TJ", "JM", "HT", "ST", "MS", "AE", "PK", "NL", "LU", "BZ", "IR", "BO", "UY", "GH", "SA", "CI", "MF", "TF", "AI", "QA", "SX", "LY", "BV", "PG", "KG", "GQ", "EH", "NU", "PR", "GD", "KR", "HM", "SM", "SL", "CD", "MK", "TR", "DZ", "GE", "PS", "BB", "UA", "GP", "PF", "NA", "BW", "SY", "TG", "DO", "AQ", "CH", "MG", "FO", "VG", "GI", "BN", "LA", "IS", "EE", "UM", "LT", "RS", "MR", "AD", "HU", "TK", "MY", "AO", "CV", "NF", "PA", "GW", "BE", "PT", "GB", "IM", "US", "YE", "HK", "AZ", "CC", "ML", "SK", "VU", "TL", "HR", "SR", "MU", "CZ", "PM", "LS", "WS", "KM", "IT", "BI", "WF", "GN", "SG", "CO", "CN", "AW", "MA", "FI", "VA", "ZW", "KY", "BH", "PY", "EC", "LR", "RU", "PL", "OM", "MT", "SS", "DE", "TM", "SJ", "MM", "TT", "IL", "BD", "NR", "LK", "UG", "NG", "BQ", "MX", "CW", "SI", "MN", "CA", "AX", "VN", "TW", "JP", "IO", "RO", "BG", "GU", "BR", "AM", "ZM", "DJ", "JE", "AT", "CM", "SE", "FJ", "KZ", "GL", "GY", "CX", "MW", "TN", "ZA", "TO", "CY", "MV", "PN", "RW", "NI", "KN", "BJ", "ET", "GM", "TZ", "VC", "FK", "SD", "MC", "AU", "CL", "DK", "FR", "TC", "CU", "AL", "MZ", "BS", "NE", "GT", "LI", "NP", "BF", "PW", "KW", "IN", "GA", "TV", "MO", "SH", "MD", "CK", "AR", "SC", "IE", "ES", "LB", "BM", "RE", "KI", "AG", "MQ", "SV", "JO", "TH", "SO", "MH", "CG", "KP", "GF", "BA", "YT", "GS", "KE", "PE", "BT", "SZ", "CR", "TD", "DM", "NC", "GR", "GG", "HN", "VI", "CF", "SN", "AF", "MP", "PH", "BY", "LV", "NO", "EG", "KH", "IQ", "LC", "NZ", "BL", "UZ", "ID", "ER", "VE", "FM", "SB", "ME", "AS"])
      # validator.allowable_values.each do |value|
      #   expect { instance.country = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "verifier"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["biomass", "dac", "forestry", "mineralization", "ocean", "renewables", "soil"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "standard_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["american_carbon_registry", "climate_action_reserve", "verified_carbon_standard", "european_biochar_certificate", "gold_standard"])
      # validator.allowable_values.each do |value|
      #   expect { instance.standard_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "longitude"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "latitude"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "production"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "organization_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
