=begin
#Patch API V1

#The core API used to integrate with Patch's service

The version of the OpenAPI document: v1
Contact: developers@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Patch::CreateFulfillmentDocumentRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Patch::CreateFulfillmentDocumentRequest do
  let(:instance) { Patch::CreateFulfillmentDocumentRequest.new }

  describe 'test an instance of CreateFulfillmentDocumentRequest' do
    it 'should create an instance of CreateFulfillmentDocumentRequest' do
      expect(instance).to be_instance_of(Patch::CreateFulfillmentDocumentRequest)
    end
  end
  describe 'test attribute "fulfillment_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
