=begin
#Patch API V1

#The core API used to integrate with Patch's service

The version of the OpenAPI document: v1
Contact: developers@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Patch::UpdatePayoutRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Patch::UpdatePayoutRequest do
  let(:instance) { Patch::UpdatePayoutRequest.new }

  describe 'test an instance of UpdatePayoutRequest' do
    it 'should create an instance of UpdatePayoutRequest' do
      expect(instance).to be_instance_of(Patch::UpdatePayoutRequest)
    end
  end
  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["accepted", "complete", "require_review"])
      # validator.allowable_values.each do |value|
      #   expect { instance.state = value }.not_to raise_error
      # end
    end
  end

end
