=begin
#Patch API V2

#The core API used to integrate with Patch's service

The version of the OpenAPI document: 2.1.0
Contact: engineering@usepatch.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

module Patch
  VERSION = '2.1.0'
end
