name: Health check
on:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build-and-test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7.1']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Ruby Dependencies
        run: bundle install

      - name: Run tests
        env:
          SANDBOX_API_KEY: ${{ secrets.SANDBOX_API_KEY }}
        run: make test

      - name: Notify slack
        uses: kpritam/slack-job-status-action@v1
        with:
          if: failure()
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: eng-notifications
