name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Install Ruby Dependencies
        run: bundle install

      - name: Run RSpec
        env:
          PATCH_RUBY_HOST: 'https://api.staging-patch.com/'
          PATCH_RUBY_API_KEY: 'key_test_1234'
        run: bundle exec rspec

